/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material 3 dark palette from the Stitch design (project 8884939569074279768)
        background: '#101419',
        'on-background': '#e0e2ea',
        surface: '#101419',
        'surface-dim': '#101419',
        'surface-bright': '#36393f',
        'surface-variant': '#31353b',
        'surface-container-lowest': '#0a0e13',
        'surface-container-low': '#181c21',
        'surface-container': '#1c2025',
        'surface-container-high': '#262a30',
        'surface-container-highest': '#31353b',
        'on-surface': '#e0e2ea',
        'on-surface-variant': '#c2c6d6',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        secondary: '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'on-secondary-container': '#c4abff',
        tertiary: '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#00a572',
        'on-tertiary-container': '#00311f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'inverse-surface': '#e0e2ea',
        'inverse-on-surface': '#2d3136',
        'inverse-primary': '#005ac2',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'stack-gap': '12px',
        'container-padding': '20px',
      },
      fontFamily: {
        // One family per weight — RN can't synthesize weights for custom fonts
        inter: ['Inter_400Regular'],
        'inter-medium': ['Inter_500Medium'],
        'inter-semibold': ['Inter_600SemiBold'],
        'inter-bold': ['Inter_700Bold'],
        mono: ['SpaceGrotesk_500Medium'],
      },
    },
  },
  plugins: [],
};
